### ISSUE TITLE
Installation "failed due to an invalid structure"

### ISSUE THREAD

**Issue by byronhallett** [mrfixit2001/plugin.video.kodikaraoke#1]
Attempted installation from zip on Kodi matrix 19.1
Installation error:
Installing the add-on from zip file located at <path> failed due to an invalid structure.

Is this the same version of Kodi you targeted when fixing the plug-in?

Thanks for your efforts!

**Comment by mrfixit2001** [comment]
Thank you for letting me know! It looks like the ZIP file that I uploaded to the repo doesn't contain a folder at the first level inside it. Kodi is picky about that. I've recreated the release and hopefully that works well now. Please let me know :)

**Comment by byronhallett** [comment]
Ahh, makes sense. Good to know for the future. The new release installs for me.
Thanks again!
