### ISSUE TITLE
youtube is not available error message

### ISSUE THREAD

**Issue by PerfectPro8** [mrfixit2001/plugin.video.kodikaraoke#5]
I keep getting YouTube is unavailable. This needs to be fixed!!. I’ve tried multiple versions of KODI  and it still doesn’t work.

**Comment by mrfixit2001** [comment]
I’ve been following this issue closely as well, it’s actually an issue with the associates YouTube plugin. Hopefully it’s resolved soon

**Comment by PerfectPro8** [comment]
Okay thank you will you let us know when the issue is fixed?

**Comment by mrfixit2001** [comment]
@PerfectPro8 YouTube's addon resolved their end, and I've made fixes on my end as well.
All set!

**Comment by mrfixit2001** [comment]
FYI - the changes in the youtube addon now require that you go through the setup process for creating an API key, ID, and secret.
https://www.firestickhow.com/youtube-api-key.html
